default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: lint
        name: lint
        always_run: true
        entry: scripts/lint.sh
        language: system
        types: [python]
